#!/usr/bin/env python3
"""Publication-spec figures for the Voynich cryptanalysis report.
Sans-serif, colourblind-safe (Okabe-Ito), 600 DPI raster + vector PDF/SVG/TIFF."""
import json, os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import rcParams

rcParams.update({'font.family':'sans-serif','font.sans-serif':['DejaVu Sans','Arial'],
                 'font.size':7,'axes.linewidth':0.6,'axes.titlesize':8,'axes.labelsize':7,
                 'xtick.labelsize':6.5,'ytick.labelsize':6.5,'legend.fontsize':6.5,
                 'savefig.dpi':600,'pdf.fonttype':42,'svg.fonttype':'none'})
OK = {'blue':'#0072B2','orange':'#E69F00','green':'#009E73','red':'#D55E00',
      'sky':'#56B4E9','purple':'#CC79A7','yellow':'#F0E442','grey':'#999999'}
MM = 1/25.4
os.makedirs('figures', exist_ok=True)
R = json.load(open('results.json'))

def save(fig, name):
    for ext in ('pdf','svg','png','tiff'):
        fig.savefig(f'figures/{name}.{ext}', bbox_inches='tight',
                    **({'pil_kwargs':{'compression':'tiff_lzw'}} if ext=='tiff' else {}))
    plt.close(fig)

LANGS = ['Voynich','Latin','Italian','German','English','Finnish','Sanskrit','Arabic']
# Voynich = red; Arabic highlighted in orange (the language claimed by Crowe 2022); rest blue
cols = [OK['red']] + [OK['blue']]*6 + [OK['orange']]
LABELS = ['Voynich','Latin','Italian','German','English','Finnish','Sanskrit','Arabic*']
n = len(LANGS)

# ---- Fig 1: entropy + word-order info ----
fig, ax = plt.subplots(1, 2, figsize=(180*MM, 72*MM))
h2 = [R['sweep'][l]['h2'] for l in LANGS]
oi = [R['sweep'][l]['order_info'] for l in LANGS]
ax[0].bar(range(n), h2, color=cols, edgecolor='black', linewidth=0.5)
ax[0].set_xticks(range(n)); ax[0].set_xticklabels(LABELS, rotation=40, ha='right')
ax[0].set_ylabel('Conditional char entropy h₂ (bits/char)')
ax[0].set_title('a  Voynichese is far more predictable than any language')
ax[0].axhline(h2[0], color=OK['red'], ls='--', lw=0.6)
ax[1].bar(range(n), oi, color=cols, edgecolor='black', linewidth=0.5)
ax[1].set_xticks(range(n)); ax[1].set_xticklabels(LABELS, rotation=40, ha='right')
ax[1].set_ylabel('Word-order information (bits)')
ax[1].set_title('b  Voynichese carries the least word-order structure')
ax[1].axhline(oi[0], color=OK['red'], ls='--', lw=0.6)
fig.text(0.5, -0.02, '*Arabic = small sample (~1.4k words); orange marks the plaintext claimed by Crowe (2022) — it clusters with the natural languages, not Voynichese.',
         ha='center', fontsize=5.5, style='italic')
save(fig, 'fig1_entropy')

# ---- Fig 2: word-length distributions ----
fig, ax = plt.subplots(figsize=(110*MM, 70*MM))
styles = {'Voynich':(OK['red'],'-','o'),'Latin':(OK['blue'],'--','s'),
          'Sanskrit':(OK['green'],'-.','^'),'Finnish':(OK['purple'],':','d'),
          'Arabic':(OK['orange'],'-','v')}
xs = list(range(1,16))
for l,(c,ls,mk) in styles.items():
    ys = [100*R['lengths'][l][str(L)] for L in xs]
    ax.plot(xs, ys, color=c, ls=ls, marker=mk, ms=2.5, lw=0.9, label=l)
ax.set_xlabel('Word length (characters)'); ax.set_ylabel('% of tokens')
ax.set_title('Voynich word length is a tight, symmetric peak'); ax.legend(frameon=False)
save(fig, 'fig2_wordlen')

# ---- Fig 3: templatic-generation evidence ----
fig, ax = plt.subplots(1, 2, figsize=(180*MM, 70*MM))
pl = ['Voynich','Latin','Sanskrit','Finnish','English']
rem = [100*(R['predict'][l]['order0']-R['predict'][l]['order2'])/R['predict'][l]['order0'] for l in pl]
ax[0].bar(range(len(pl)), rem, color=[OK['red']]+[OK['blue']]*4, edgecolor='black', linewidth=0.5)
ax[0].set_xticks(range(len(pl))); ax[0].set_xticklabels(pl, rotation=40, ha='right')
ax[0].set_ylabel('% uncertainty removed by local context')
ax[0].set_title('a  Voynich words are the most templatic')
fl = ['Voynich','Latin','Sanskrit','Finnish']
mass = [R['factored'][l]['mass'] for l in fl]
ax[1].bar(range(len(fl)), mass, color=[OK['red']]+[OK['blue']]*3, edgecolor='black', linewidth=0.5)
ax[1].set_xticks(range(len(fl))); ax[1].set_xticklabels(fl, rotation=40, ha='right')
ax[1].set_ylabel('% real token-mass regenerated by\nindependent prefix×middle×suffix sampling')
ax[1].set_title('b  A finite-state slot model rebuilds the Voynich lexicon')
save(fig, 'fig3_templatic')

# ---- Fig 4: per-section fingerprint (verified values from cryptanalysis2 run) ----
SEC = ['Herbal','Biological','Pharma','Stars/rec.','Cosmo']
sec_h2 = [2.21,1.81,2.08,2.00,2.06]
sec_gal = [22.4,16.6,23.0,27.2,20.1]      # 1st-word gallows %
sec_body = [8.0,4.3,3.7,5.6,6.2]
fig, ax = plt.subplots(1, 2, figsize=(180*MM, 70*MM))
ax[0].bar(range(5), sec_h2, color=OK['purple'], edgecolor='black', linewidth=0.5)
ax[0].set_xticks(range(5)); ax[0].set_xticklabels(SEC, rotation=40, ha='right')
ax[0].set_ylabel('h₂ (bits/char)'); ax[0].set_ylim(0,3)
ax[0].axhline(3.3, color=OK['grey'], ls='--', lw=0.6); ax[0].text(0,3.32,'natural-language level',fontsize=6,color=OK['grey'])
ax[0].set_title('a  Every section is abnormally low-entropy')
w=0.38
ax[1].bar([i-w/2 for i in range(5)], sec_gal, w, color=OK['orange'], edgecolor='black', linewidth=0.5, label='line-initial word')
ax[1].bar([i+w/2 for i in range(5)], sec_body, w, color=OK['sky'], edgecolor='black', linewidth=0.5, label='other words')
ax[1].set_xticks(range(5)); ax[1].set_xticklabels(SEC, rotation=40, ha='right')
ax[1].set_ylabel('% of words starting with a gallows glyph')
ax[1].set_title('b  Line-as-unit effect present in every section'); ax[1].legend(frameon=False)
save(fig, 'fig4_sections')

# ---- Fig 5: reverse/mirror — initial vs final glyph distribution ----
fig, ax = plt.subplots(figsize=(110*MM, 65*MM))
first = R['reverse']['first']; last = R['reverse']['last']
glyphs = sorted(set(first)|set(last))
import numpy as np
fi = [first.get(g,0) for g in glyphs]; la = [last.get(g,0) for g in glyphs]
sf=sum(fi); sl=sum(la)
x=np.arange(len(glyphs))
ax.bar(x-0.2, [100*v/sf for v in fi], 0.4, color=OK['green'], edgecolor='black', linewidth=0.4, label='word-initial')
ax.bar(x+0.2, [100*v/sl for v in la], 0.4, color=OK['red'], edgecolor='black', linewidth=0.4, label='word-final')
ax.set_xticks(x); ax.set_xticklabels(glyphs)
ax.set_xlabel('EVA glyph'); ax.set_ylabel('% of word positions')
ax.set_title(f'Start and end use near-disjoint glyphs (KL = {R["reverse"]["kl"]:.1f} bits)\n=> strongly directional; reversal/mirror only swaps the ends')
ax.legend(frameon=False)
save(fig, 'fig5_directionality')

print("figures written:", sorted(set(f.split('.')[0] for f in os.listdir('figures'))))
