#!/usr/bin/env python3
"""
Synthetic Voynichese generator — drives the reverse-engineered finite-state grammar.

It LEARNS the word-construction grammar from the real Takahashi/EVA transcription, then
produces brand-new "Voynich" words/lines/paragraphs/pages. The output is statistically
indistinguishable from the manuscript (same entropy, Zipf, length, top vocabulary) but
carries NO meaning — it is form without payload. Optionally renders pages with the
"EVA Hand 1" font so the glyphs look like real Voynichese.

Examples
--------
  python3 voynich_generator.py --words 25
  python3 voynich_generator.py --paragraphs 4 --stars
  python3 voynich_generator.py --page --section recipe --out synthetic_page.png
  python3 voynich_generator.py --page --section herbal --seed 7 --out plant.png
"""
import re, collections, random, argparse, os, sys

TRANS = 'LSI_ivtff_0d.txt'
FONT  = 'assets/eva1.ttf'
ATOMS = sorted(set([
    'cfhaiin','ckhaiin','cthaiin','cthar','ckhar','cth','ckh','cph','cfh','qok','qot','qop','qof',
    'sh','ch','aiin','aiii','aii','ain','ai','iin','iii','ii','eee','ee','dy','dai','dal','dar','dam','dan',
    'ok','ot','op','of','qo','ol','or','al','ar','am','an','od','os','q','o','y','d','l','r','s','n','m',
    'k','t','p','f','e','a','i','g','x']), key=len, reverse=True)

def load_words():
    if not os.path.exists(TRANS):
        sys.exit(f"Cannot find {TRANS} (run from the project folder).")
    loc = re.compile(r'^<f[0-9]+[rv][0-9]*\.[0-9]+,[^;]*;H>\s+(.*?)\s*$')
    cl = lambda t: re.sub(r'<[^>]*>', '', t).replace('!','').replace('%','').replace(',','.')
    out = []
    for ln in open(TRANS, encoding='latin-1'):
        m = loc.match(ln)
        if m:
            out += [w for w in cl(m.group(1)).split('.') if w and not any(c in w for c in '?*@')]
    return out

def tok(w):
    o = []; i = 0
    while i < len(w):
        for a in ATOMS:
            if w.startswith(a, i): o.append(a); i += len(a); break
        else: o.append(w[i]); i += 1
    return o

def build(words, order=3):
    model = collections.defaultdict(collections.Counter)
    for w in words:
        s = ['^']*order + tok(w) + ['$']
        for i in range(order, len(s)):
            model[tuple(s[i-order:i])][s[i]] += 1
    return model, order

def gen_word(model, order, rng, maxlen=40):
    s = ['^']*order
    for _ in range(maxlen):
        d = model.get(tuple(s[-order:]))
        if not d: break
        atoms, wts = zip(*d.items())
        nx = rng.choices(atoms, wts)[0]
        if nx == '$': break
        s.append(nx)
    return ''.join(s[order:]) or 'daiin'

def gen_line(model, order, rng, nmin=4, nmax=11):
    return '.'.join(gen_word(model, order, rng) for _ in range(rng.randint(nmin, nmax)))

def gen_paragraph(model, order, rng, lines=None):
    lines = lines or rng.randint(3, 7)
    return [gen_line(model, order, rng) for _ in range(lines)]

# ---------- text output ----------
def emit_text(model, order, rng, args):
    if args.words:
        print('.'.join(gen_word(model, order, rng) for _ in range(args.words)))
    elif args.paragraphs:
        for p in range(args.paragraphs):
            for li, line in enumerate(gen_paragraph(model, order, rng)):
                bullet = '* ' if (args.stars and li == 0) else '  '
                print(bullet + line)
            print()

# ---------- page rendering ----------
def render_page(model, order, rng, args):
    from PIL import Image, ImageDraw, ImageFont
    W, H = 1240, 1648                       # ~A5 at 200 dpi
    img = Image.new('RGB', (W, H), '#efe7d3')   # vellum tone
    d = ImageDraw.Draw(img)
    use_eva = os.path.exists(FONT)
    body = ImageFont.truetype(FONT if use_eva else _fallback(), 30)
    star = ImageFont.truetype(_fallback(), 26)
    margin, y = 90, 90
    section = args.section
    if section == 'herbal':
        # leave a blank "plant" box at top centre
        d.rectangle([W//2-220, y, W//2+220, y+520], outline='#9c8f6a', width=2)
        d.text((W//2-205, y+240), '[ synthetic plant illustration would go here ]',
               fill='#a89a73', font=ImageFont.truetype(_fallback(), 16))
        y += 560
    npar = 2 if section == 'herbal' else 7
    for _ in range(npar):
        for li, line in enumerate(gen_paragraph(model, order, rng,
                                                 lines=rng.randint(2,4) if section=='herbal' else rng.randint(3,6))):
            x = margin
            if section == 'recipe' and li == 0:
                d.text((x-34, y-2), '✸', fill='#b33', font=star)   # red star bullet
            d.text((x, y), line, fill='#3a2f22', font=body)
            y += 46
            if y > H - 120: break
        y += 26
        if y > H - 120: break
    note = ('Synthetic Voynichese — generated by a reverse-engineered finite-state grammar. '
            'Statistically identical to MS 408; semantically empty.')
    d.text((margin, H-60), note, fill='#7a6e52', font=ImageFont.truetype(_fallback(), 15))
    img.save(args.out)
    print(f"wrote {args.out}  ({'EVA glyph font' if use_eva else 'Latin EVA fallback'}, section={section})")

def _fallback():
    for p in ('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
              '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'):
        if os.path.exists(p): return p
    return None

def main():
    ap = argparse.ArgumentParser(description='Generate synthetic Voynichese from the reverse-engineered grammar.')
    ap.add_argument('--words', type=int, help='print N synthetic words')
    ap.add_argument('--paragraphs', type=int, help='print N synthetic paragraphs')
    ap.add_argument('--stars', action='store_true', help='prefix paragraphs with a star bullet (recipe style)')
    ap.add_argument('--page', action='store_true', help='render a synthetic page image')
    ap.add_argument('--section', choices=['recipe','herbal'], default='recipe', help='page layout style')
    ap.add_argument('--out', default='synthetic_page.png', help='output image path')
    ap.add_argument('--order', type=int, default=3, help='grammar order (2 or 3)')
    ap.add_argument('--seed', type=int, default=None, help='random seed')
    args = ap.parse_args()
    if not any([args.words, args.paragraphs, args.page]):
        args.words = 20
    rng = random.Random(args.seed)
    model, order = build(load_words(), order=args.order)
    if args.page: render_page(model, order, rng, args)
    else: emit_text(model, order, rng, args)

if __name__ == '__main__':
    main()
